[package]
name = "rust-microservices"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.5.3"
futures = "0.1.17"
hyper = "0.11.13"
log = "0.4.1"
url = "2.2"
serde_json = "1.0"
diesel = { version = "1.0.0", features = ["postgres"] }
maud = "0.25"
